version: '3.1'
services:
  my_test:
    image: my_test:v1.0.0
    container_name: my_test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/go/src